---
- name: install plugins listed in appian_local_plugins_list
  copy:
    src: "{{ item }}"
    dest: "{{ appian_home }}/_admin/plugins/"
    owner: "appian"
    group: "root"
    mode: 0764
  become: yes
  with_items: "{{ appian_local_plugins_list }}"

- name: install plugins listed in appian_remote_plugins_list
  get_url:
    url: "{{ item }}"
    dest: "{{ appian_home }}/_admin/plugins/"
    owner: "appian"
    group: "root"
    mode: 0764
  become: yes
  with_items: "{{ appian_remote_plugins_list }}"
