---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: appian
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - molecule_web_war:/web_war
    privileged: true
    pre_build_image: true
    networks:
      - name: molecule
  - name: mysql
    image: "mysql:5.7"
    privileged: true
    pre_build_image: true
    override_command: false
    networks:
      - name: molecule
    env:
      MYSQL_ROOT_PASSWORD: dbPW123!bang
      MYSQL_DATABASE: APPIAN
  - name: apache
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - molecule_web_war:/web_war
    privileged: true
    pre_build_image: true
    published_ports:
      - "80:80"
    networks:
      - name: molecule
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    hosts:
      all:
        hosts:
          appian:
          mysql:
            engine: mysql
            master_username: root
            endpoint:
              address: mysql
              port: 3306
            db_name: APPIAN
      appian_instances:
        hosts:
          appian:
          apache:
      appian_engines_instances:
        hosts:
          appian:
      appian_internal_messaging_instances:
        hosts:
          appian:
      appian_data_server_instances:
        hosts:
          appian:
      appian_search_server_instances:
        hosts:
          appian:
      appian_app_server_instances:
        hosts:
          appian:
      appian_web_server_instances:
        hosts:
          apache:
      appian_leader:
        hosts:
          appian:
      appiands:
        hosts:
          mysql:
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
