---
- name: Converge
  hosts: appian_instances
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: cmsgov.appian

- name: docker only - copy web.war to shared volume
  hosts: appian_leader
  vars_files:
    - vars.yml
  tasks:
    - name: copy web.war from appian to shared volume
      command: "cp -a /opt/appian/appian/deployment/web.war/. /web_war/"

- name: docker only - copy shared volume to /var/www/suite
  hosts: appian_web_server_instances
  vars_files:
    - vars.yml
  tasks:
    - name: copy web.war from shared volume to apache
      command: "cp -a /web_war/. /var/www/suite/"

    - name: correct permissions on /var/www/suite
      file:
        path: "/var/www/suite"
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: true
      become: yes
